version: '2'
volumes:
  rabbit_data:
services:
  rabbit:
    image: mileschet/rabbitmq
    ports:
      - "5672:5672"
      - "15674:15674"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
